import type * as monaco from "monaco-editor";

export type MonacoOptions = monaco.editor.IStandaloneEditorConstructionOptions;

export const defaultSettings: MonacoOptions = {
  scrollBeyondLastLine: false,
  wordWrap: "on",
  wordWrapColumn: 80,
  theme: undefined,
  acceptSuggestionOnCommitCharacter: true,
  acceptSuggestionOnEnter: "on",
  accessibilityPageSize: 10,
  accessibilitySupport: "auto",
  autoClosingBrackets: "languageDefined",
  autoClosingOvertype: "auto",
  autoClosingQuotes: "languageDefined",
  autoIndent: "advanced",
  autoSurround: "languageDefined",
  comments: {
    insertSpace: true,
  },
  contextmenu: true,
  copyWithSyntaxHighlighting: true,
  cursorBlinking: "blink",
  cursorSmoothCaretAnimation: "off",
  cursorStyle: "line",
  cursorWidth: 0,
  cursorSurroundingLines: 0,
  cursorSurroundingLinesStyle: "default",
  detectIndentation: true,
  dragAndDrop: true,
  emptySelectionClipboard: true,
  fastScrollSensitivity: 5,
  find: {
    addExtraSpaceOnTop: true,
    autoFindInSelection: "never",
    seedSearchStringFromSelection: "always",
  },
  folding: true,
  foldingHighlight: true,
  foldingStrategy: "auto",
  fontFamily: undefined,
  fontLigatures: false,
  fontSize: undefined,
  fontWeight: "normal",
  glyphMargin: false,
  hideCursorInOverviewRuler: false,
  insertSpaces: true,
  letterSpacing: 0,
  lineDecorationsWidth: 10,
  lineHeight: 0,
  lineNumbers: "on",
  links: true,
  matchBrackets: "always",
  mouseStyle: "text",
  mouseWheelScrollSensitivity: 1,
  mouseWheelZoom: false,
  multiCursorMergeOverlapping: true,
  multiCursorModifier: "alt",
  multiCursorPaste: "spread",
  occurrencesHighlight: true,
  overviewRulerBorder: true,
  quickSuggestions: true,
  quickSuggestionsDelay: 10,
  renderControlCharacters: false,
  renderFinalNewline: "on",
  renderLineHighlight: "line",
  renderWhitespace: "none",
  roundedSelection: true,
  rulers: [],
  scrollBeyondLastColumn: 5,
  selectOnLineNumbers: true,
  selectionHighlight: true,
  showFoldingControls: "mouseover",
  smoothScrolling: false,
  suggestSelection: "recentlyUsed",
  suggest: {
    filterGraceful: true,
    insertMode: "insert",
    localityBonus: false,
    shareSuggestSelections: false,
  },
  suggestFontSize: undefined,
  suggestLineHeight: undefined,
  suggestOnTriggerCharacters: true,
  tabCompletion: "off",
  tabSize: 4,
  trimAutoWhitespace: true,
  useTabStops: true,
  wordBasedSuggestions: true,
  wordSeparators: "`~!@#$%^&*()-=+[{]}\\|;:'\",.<>/?",
  wrappingIndent: "none",
  wrappingStrategy: "simple",
};
